services:
  - type: web
    name: gestionappucao
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Recouvrement UCAO"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: SEED_DB
        value: "true"
