databases:
  - name: gestionappucao-db
    plan: free
    databaseName: gestionappucao
    user: gestionappucao

services:
  - type: web
    name: gestionappucao
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Recouvrement UCAO"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: gestionappucao-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gestionappucao-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: gestionappucao-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gestionappucao-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gestionappucao-db
          property: password
      - key: SEED_DB
        value: "true"
